config/routes.rb
Pilotaz::Application.routes.draw do
  resources :aktualnis

  get "pilots/index"

  get "/export" => 'pilots#export'
  get "/pilots/export" => 'pilots#export'  

  resources :pilots

  root :to => 'pilots#index'

end

app/models/aktualni.rb
class Aktualni < ActiveRecord::Base
  attr_accessible :begin, :pilot
end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
  attr_accessible :begin, :end, :note, :pilot
end

app/controllers/aktualnis_controller.rb
class AktualnisController < ApplicationController
  # GET /aktualnis
  # GET /aktualnis.json
  def index
    @aktualnis = Aktualni.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aktualnis }
    end
  end

  # GET /aktualnis/1
  # GET /aktualnis/1.json
  def show
    @aktualni = Aktualni.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aktualni }
    end
  end

  # GET /aktualnis/new
  # GET /aktualnis/new.json
  def new
    @aktualni = Aktualni.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aktualni }
    end
  end

  # GET /aktualnis/1/edit
  def edit
    @aktualni = Aktualni.find(params[:id])
  end

  # POST /aktualnis
  # POST /aktualnis.json
  def create
    @aktualni = Aktualni.new(params[:aktualni])

    respond_to do |format|
      if @aktualni.save
        format.html { redirect_to pilots_path, notice: 'Pilot successully changed' }
        format.json { render json: @aktualni, status: :created, location: @aktualni }
      else
        format.html { render action: "new" }
        format.json { render json: @aktualni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aktualnis/1
  # PUT /aktualnis/1.json
  def update
    @aktualni = Aktualni.find(params[:id])

    respond_to do |format|
      if @aktualni.update_attributes(params[:aktualni])
        format.html { redirect_to @aktualni, notice: 'Aktualni was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aktualni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aktualnis/1
  # DELETE /aktualnis/1.json
  def destroy
    @aktualni = Aktualni.find(params[:id])
    @aktualni.destroy

    respond_to do |format|
      format.html { redirect_to aktualnis_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  # GET /pilots
  # GET /pilots.json
  def index
    @pilots = Pilot.where("begin > ? ", Date.yesterday).order('begin')
    @aktualnis= Aktualni.last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pilots }
    end
  end

  # GET /export
  # GET /export.json
#  def export1
#    @pilots = Pilot.order('begin')
#    @aktualnis= Aktualni.last

#    respond_to do |format|
#      format.html
#      format.json {render json: {:current => @aktualnis, :pilots => @pilots}}
#    end
#  end

  def export
    @pilots = Pilot.where("begin > ? ", Date.yesterday).order('begin')
    @aktualnis= Aktualni.last


 #   Jbuilder.encode do |json|
 # 	json.(@aktualnis, :pilot, :begin)

 # 	json.author do
 #   		json.pilot @pilots.pilot
 #   		json.begin @message.begin
 # 	end

 #   end
  end


  # GET /pilots/1
  # GET /pilots/1.json
  def show
    @pilot = Pilot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pilot }
    end
  end

  # GET /pilots/new
  # GET /pilots/new.json
  def new
    @pilot = Pilot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pilot }
    end
  end

  # GET /pilots/1/edit
  def edit
    @pilot = Pilot.find(params[:id])
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(params[:pilot])
    respond_to do |format|
  #   if @pilot.save 
   
      if @pilot.save
	@pilot.update_attributes(:end => @pilot.end.change(:year => @pilot.begin.year, :month => @pilot.begin.month, :day => @pilot.begin.day))
        if @pilot.end < @pilot.begin
	  @pilot.update_attributes(:end =>  @pilot.end + 1.days)
	end
        format.html { redirect_to pilots_path, notice: 'Pilot was successfully created.' }
        format.json { render json: @pilot, status: :created, location: @pilot }
      else
        format.html { render action: "new" }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pilots/1
  # PUT /pilots/1.json
  def update
    @pilot = Pilot.find(params[:id])

    respond_to do |format|
      if @pilot.update_attributes(params[:pilot])
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot = Pilot.find(params[:id])
    @pilot.destroy

    respond_to do |format|
      format.html { redirect_to pilots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aktualnis_helper.rb
module AktualnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/aktualnis/_form.html.erb
<%= form_for(@aktualni) do |f| %>
  <% if @aktualni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aktualni.errors.count, "error") %> prohibited this aktualni from being saved:</h2>

      <ul>
      <% @aktualni.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begin %><br />
    <%= f.datetime_select :begin %>
  </div>
  <div class="field">
    <%= f.label :pilot %><br />
    <%= f.text_field :pilot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aktualnis/edit.html.erb
<h1>Editing aktualni</h1>

<%= render 'form' %>

<%= link_to 'Show', @aktualni %> |
<%= link_to 'Back', aktualnis_path %>

app/views/aktualnis/index.html.erb
<h1>Listing aktualnis</h1>

<table>
  <tr>
    <th>Begin</th>
    <th>Pilot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aktualnis.each do |aktualni| %>
  <tr>
    <td><%= aktualni.begin %></td>
    <td><%= aktualni.pilot %></td>
    <td><%= link_to 'Show', aktualni %></td>
    <td><%= link_to 'Edit', edit_aktualni_path(aktualni) %></td>
    <td><%= link_to 'Destroy', aktualni, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aktualni', new_aktualni_path %>

app/views/aktualnis/new.html.erb
<h1>New aktualni</h1>

<%= render 'form' %>

<%= link_to 'Back', aktualnis_path %>

app/views/aktualnis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Begin:</b>
  <%= @aktualni.begin %>
</p>

<p>
  <b>Pilot:</b>
  <%= @aktualni.pilot %>
</p>


<%= link_to 'Edit', edit_aktualni_path(@aktualni) %> |
<%= link_to 'Back', aktualnis_path %>

app/views/home/index.html.erb
<%= link_to "Pilotaz", pilots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pilotaz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pilots/_form.html.erb
<%= form_for(@pilot) do |f| %>
  <% if @pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
      <% @pilot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begin %><br />
    <%= f.datetime_select :begin %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.time_select :end %>
  </div>
  <div class="field">
    <%= f.label :pilot %><br />
    <%= f.text_field :pilot %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Editing pilot</h1>

<%= render 'form' %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>

app/views/pilots/index.html.erb
<h1>Robotice flight controll</h1>
<p id="notice"><%= notice %></p>
<br>
pilot is: <b> <%= @aktualnis.pilot %> </b> since: <%= @aktualnis.begin.strftime("%a %d.%m. %H:%M")%>
<br>
<%= link_to 'Take wheel', new_aktualni_path %>
<br>
<br>


<table border=1>
  <tr>
    <th>Time</th>

    <th>Pilot</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pilots.each do |pilot| %>
  <tr>
    <td><%= pilot.begin.strftime("%a %d.%m. %H:%M")%> -- <%= pilot.end.strftime("%H:%M") %></td>

    <td><%= pilot.pilot %></td>
    <td><%= pilot.note %></td>
    <td><%= link_to 'Show', pilot %></td>
    <td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
    <td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New entry', new_pilot_path %>

<br />

app/views/pilots/new.html.erb
<h1>New pilot</h1>

<%= render 'form' %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Begin:</b>
  <%= @pilot.begin %>
</p>

<p>
  <b>End:</b>
  <%= @pilot.end %>
</p>

<p>
  <b>Pilot:</b>
  <%= @pilot.pilot %>
</p>

<p>
  <b>Note:</b>
  <%= @pilot.note %>
</p>


<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>